# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My Blog
email: robert@bonaroo.nl
legal_entity: Charper Bonaroo B.V.
description: >- 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://roberthopman.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag

show_excerpts: false

author:
  name: Robert Hopman
  email: "robert@bonaroo.nl"

disqus:
  shortname: roberthopman

minima:
  social_links:
    github: roberthopman
    stackoverflow: "6430382"
    twitter: roberthopman
    
google_analytics: 'G-J0HMLHK67L'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
